# Generated by Django 6.0.7 on 2026-07-28 05:19
"""
BEGIN;
--
-- Create model CreditCard
--
CREATE TABLE "credit_cards_creditcard" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "name" varchar(150) NOT NULL, "issuer" varchar(50) NOT NULL, "last_four_digits" varchar(4) NOT NULL, "credit_limit" numeric(12, 2) NOT NULL, "closing_day" smallint NOT NULL CHECK ("closing_day" >= 0), "payment_due_day" smallint NOT NULL CHECK ("payment_due_day" >= 0), "user_id" uuid NOT NULL);
ALTER TABLE "credit_cards_creditcard" ADD CONSTRAINT "credit_cards_creditcard_user_id_02b21ddc_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "credit_cards_creditcard_user_id_02b21ddc" ON "credit_cards_creditcard" ("user_id");
COMMIT;
"""

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("issuer", models.CharField(max_length=50)),
                (
                    "last_four_digits",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Last four digits must be empty or contain exactly 4 digits",
                                regex="^$|^\\d{4}$",
                            )
                        ],
                    ),
                ),
                ("credit_limit", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "closing_day",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ]
                    ),
                ),
                (
                    "payment_due_day",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
