# Generated by Django 6.0.7 on 2026-07-28 06:14
"""
BEGIN;
--
-- Create model Transaction
--
CREATE TABLE "transactions_transaction" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "name" varchar(150) NOT NULL, "description" text NOT NULL, "amount" numeric(12, 2) NOT NULL, "movement_type" varchar(8) NOT NULL, "payment_method" varchar(8) NOT NULL, "transaction_date" date NOT NULL, "category_id" uuid NOT NULL, "credit_card_id" uuid NULL, "subscription_id" uuid NULL, "user_id" uuid NOT NULL);
ALTER TABLE "transactions_transaction" ADD CONSTRAINT "transactions_transac_category_id_c06a92e3_fk_categorie" FOREIGN KEY ("category_id") REFERENCES "categories_category" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "transactions_transaction" ADD CONSTRAINT "transactions_transac_credit_card_id_97fcd84e_fk_credit_ca" FOREIGN KEY ("credit_card_id") REFERENCES "credit_cards_creditcard" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "transactions_transaction" ADD CONSTRAINT "transactions_transac_subscription_id_4269e14e_fk_subscript" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions_subscription" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "transactions_transaction" ADD CONSTRAINT "transactions_transaction_user_id_b9ecc248_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "transactions_transaction_category_id_c06a92e3" ON "transactions_transaction" ("category_id");
CREATE INDEX "transactions_transaction_credit_card_id_97fcd84e" ON "transactions_transaction" ("credit_card_id");
CREATE INDEX "transactions_transaction_subscription_id_4269e14e" ON "transactions_transaction" ("subscription_id");
CREATE INDEX "transactions_transaction_user_id_b9ecc248" ON "transactions_transaction" ("user_id");
COMMIT;
"""

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("credit_cards", "0001_initial"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        max_length=8,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("debit", "Debit"),
                            ("credit", "Credit"),
                        ],
                        max_length=8,
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="categories.category",
                    ),
                ),
                (
                    "credit_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="credit_cards.creditcard",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
