# Generated by Django 6.0.7 on 2026-07-28 14:48

"""
BEGIN;
--
-- Rename field title on category to name
--
ALTER TABLE "categories_category" RENAME COLUMN "title" TO "name";
COMMIT;
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="title",
            new_name="name",
        ),
    ]
