# Generated by Django 6.0.7 on 2026-07-28 05:49
"""
BEGIN;
--
-- Create model Subscription
--
CREATE TABLE "subscriptions_subscription" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "name" varchar(150) NOT NULL, "amount" numeric(12, 2) NOT NULL, "billing_cycle" varchar(10) NOT NULL, "next_payment_date" date NOT NULL, "payment_method" varchar(8) NOT NULL, "category_id" uuid NOT NULL, "credit_card_id" uuid NULL, "user_id" uuid NOT NULL);
ALTER TABLE "subscriptions_subscription" ADD CONSTRAINT "subscriptions_subscr_category_id_8d7f3e81_fk_categorie" FOREIGN KEY ("category_id") REFERENCES "categories_category" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions_subscription" ADD CONSTRAINT "subscriptions_subscr_credit_card_id_2250e1d2_fk_credit_ca" FOREIGN KEY ("credit_card_id") REFERENCES "credit_cards_creditcard" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "subscriptions_subscription" ADD CONSTRAINT "subscriptions_subscription_user_id_a353e93d_fk_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "subscriptions_subscription_category_id_8d7f3e81" ON "subscriptions_subscription" ("category_id");
CREATE INDEX "subscriptions_subscription_credit_card_id_2250e1d2" ON "subscriptions_subscription" ("credit_card_id");
CREATE INDEX "subscriptions_subscription_user_id_a353e93d" ON "subscriptions_subscription" ("user_id");
COMMIT;
"""

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("credit_cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                            ("weekly", "Weekly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("next_payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("debit", "Debit"),
                            ("credit", "Credit"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="categories.category",
                    ),
                ),
                (
                    "credit_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="credit_cards.creditcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
